/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── New design system (navy / red) ──────────────────────────────
        "primary":                    "#0F1729",
        "primary-container":          "#131b2d",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#94a0c0",
        "secondary":                  "#b7102a",
        "secondary-container":        "#db313f",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#fffbff",
        "tertiary":                   "#457b9d",
        "tertiary-container":         "#001e2e",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#548aac",
        "surface":                    "#f8f9fa",
        "surface-dim":                "#d9dadb",
        "surface-bright":             "#f8f9fa",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f4f5",
        "surface-container":          "#edeeef",
        "surface-container-high":     "#e7e8e9",
        "surface-container-highest":  "#e1e3e4",
        "surface-variant":            "#e1e3e4",
        "on-surface":                 "#191c1d",
        "on-surface-variant":         "#45464c",
        "inverse-surface":            "#2e3132",
        "inverse-on-surface":         "#f0f1f2",
        "background":                 "#f1f3f5",
        "on-background":              "#191c1d",
        "outline":                    "#76777d",
        "outline-variant":            "#c6c6cd",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        // ── Original design tokens (Aether / dark theme) ────────────────
        dark: {
          50:  '#000000',
          100: '#050505',
          200: '#0a0a0a',
          300: '#111111',
          400: '#1a1a1a',
          500: '#222222',
        },
        gold: {
          300: '#f87171',
          400: '#e11d2c',
          500: '#e11d2c',
          600: '#b3121f',
          700: '#7f0d15',
        },
        brand: '#e11d2c',
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "1rem",
        "full":    "9999px",
      },
      spacing: {
        "xs":                "8px",
        "sm":                "12px",
        "md":                "16px",
        "lg":                "24px",
        "xl":                "32px",
        "2xl":               "48px",
        "sidebar-width":     "240px",
        "header-height":     "64px",
        "gutter":            "24px",
        "base":              "4px",
        "stack-sm":          "8px",
        "stack-md":          "16px",
        "stack-lg":          "32px",
        "container-padding": "24px",
        "unit":              "4px",
      },
      fontFamily: {
        "sans":      ["Public Sans", "system-ui", "sans-serif"],
        "body":      ["Public Sans", "system-ui", "sans-serif"],
        "heading":   ['"Instrument Serif"', "Georgia", "serif"],
        "mono-data": ["Courier Prime", "monospace"],
      },
      fontSize: {
        "display-lg":  ["2.75rem",  { lineHeight: "3.25rem",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["1.875rem", { lineHeight: "2.375rem", fontWeight: "700" }],
        "headline-md": ["1.375rem", { lineHeight: "1.875rem", fontWeight: "600" }],
        "headline-sm": ["1.0625rem",{ lineHeight: "1.625rem", fontWeight: "600" }],
        "body-lg":     ["1rem",     { lineHeight: "1.5rem" }],
        "body-md":     ["0.875rem", { lineHeight: "1.25rem" }],
        "body-sm":     ["0.8125rem",{ lineHeight: "1.125rem" }],
        "label-md":    ["0.75rem",  { lineHeight: "1rem",     letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm":    ["0.6875rem",{ lineHeight: "1rem",     fontWeight: "600" }],
      },
      boxShadow: {
        "sm":      "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "DEFAULT": "0 2px 6px rgba(0,0,0,0.07), 0 1px 3px rgba(0,0,0,0.04)",
        "md":      "0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)",
        "lg":      "0 8px 24px rgba(0,0,0,0.10), 0 4px 8px rgba(0,0,0,0.04)",
        "gold":    "0 0 24px rgba(225,29,44,0.20)",
        "gold-lg": "0 0 48px rgba(225,29,44,0.28)",
        "card":    "0 4px 32px rgba(0,0,0,0.6)",
        "glass":   "inset 0 0 0 1px rgba(255,255,255,0.10)",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      animation: {
        'shimmer':  'shimmer 1.5s infinite',
        'fade-up':  'fade-up 0.6s ease-out forwards',
        'blur-in':  'blur-in 0.8s ease-out forwards',
        'kenburns': 'ae-kenburns 18s ease-in-out infinite alternate',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-up': {
          '0%':   { opacity: 0, transform: 'translateY(24px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        'blur-in': {
          '0%':   { filter: 'blur(10px)', opacity: 0, transform: 'translateY(20px)' },
          '100%': { filter: 'blur(0)',    opacity: 1, transform: 'translateY(0)' },
        },
        'ae-kenburns': {
          '0%':   { transform: 'scale(1.0) translate(0,0)' },
          '100%': { transform: 'scale(1.08) translate(-1%,-1%)' },
        },
      },
    },
  },
  plugins: [],
}
