apiVersion: v1
kind: Secret
metadata:
  name: nipponbid-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOST: "mysql-headless.{{ .Values.namespace }}.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.cloudinaryCloudName | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.cloudinaryApiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.cloudinaryApiSecret | quote }}
